### PR TITLE
Specify graphql_client_codegen version

### PR DESCRIPTION
**Pull request by h-michael**
- specify dependency version

### CODE REVIEW

**Comment by tomhoule** [comment]
It makes sense indeed. I don't have enough experience with publishing multi-crate projects, but I think we should push graphql_client_codegen to crates.io at the same time as the next release of graphql-client (hopefully in the next 10 days, I'm going to give a small presentation to a local meetup about the library and it would be nice to have a new release - there are a lot of awesome unreleased features now). Do you have more experience/ideas on that topic?

**Comment by h-michael** [comment]
@tomhoule 
Now we have the same version of each crate,
but what if we make breaking changes only on dependent crate?

**Comment by tomhoule** [comment]
I'll try to read up on this - but I think it's maybe good to keep all crates at the same version because users should only import `graphql_client` and not the others.

**Comment by h-michael** [comment]
> I'll try to read up on this

Sorry, what's this you said ?

**Comment by tomhoule** [comment]
Maybe there are blog posts or articles with good solutions to this problem.

**Pull request merged**
